name: Build Alpine Image

on:
  push:
    branches:
      - alpine
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: alpine

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO }}:alpine .
          docker push ghcr.io/${{ env.REPO }}:alpine
